name: zukko_books
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #infrastructure
  shared_preferences: ^2.0.8
  dartz: ^0.10.0
  flutter_bloc: ^7.3.1
  freezed: ^0.15.0+1
  chopper: ^4.0.1
  connectivity: ^3.0.6
  built_value: ^8.1.2

  #ui
  flutter_screenutil: ^5.0.0+2
  easy_localization: ^3.0.0
  flutter_svg: ^0.23.0+1
  pinput: ^1.2.2
  cached_network_image: any
  shimmer: any
  mask_text_input_formatter: ^2.0.0
  no_glow_scroll: ^0.0.2
  flutter_rating_stars: ^1.0.3+4
  platform: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_bloc_generator: ^1.0.0
  freezed_annotation: ^0.15.0
  build_runner: ^2.1.4
  chopper_generator: ^4.0.2
  built_value_generator: ^8.1.2

  flutter_native_splash: ^1.3.2




flutter_native_splash: 
  color: "#3F51B5"
  image: assets/zukko.png



flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/svgs/
    - assets/translation/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

